application: economistvocabulary
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /index
  script: main.appIndex

- url: /add
  script: main.appAdd


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
